version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - dynamodb-network
    command: node ./src/index.js

  dynamodb-local:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - '8000:8000'
    expose:
      - '8000'
    networks:
      - dynamodb-network

networks:
  dynamodb-network:
    driver: bridge
