version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb
    links:
      - dynamodb
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - app-network
    command: node ./src/index.js
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - '8000:8000'
    expose:
      - '8000'

networks:
  app-network:
    driver: bridge
